language: ruby

sudo: false

addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
  services:
    - elasticsearch

before_install:
  - sleep 10

install: true

script:
  - cat ~/apt-get-update.log
  - elasticsearch -v
  - curl http://localhost:9200/
