language: ruby

rvm:
  - jruby-d19

addons:
  apt:
    packages:
      - qt4-qmake

env:
  global:
    - JRUBY_OPTS=-Xcext.enabled=true

sudo: false

before_install:
  - find `rvm config-get prefix` -name mkmf.rb -print -exec sed -i 's/\s*\(abort "mkmf\)/# \1/' {} \;

script: true

notifications:
  email: true
