language: ruby

sudo: required

services:
  - docker

install: true

script: true

deploy:
  provider: heroku
  edge:
    branch: heroku-curl-debug
  verbose: true
  retry: 5
  api_key: foobar
  on:
    all_branches: true
