sudo: false
language: ruby
rvm:
- "2.2.2"


addons:
    postgresql: "9.4"

#install:
#- bundle install
# cannot override default install:  or caching will stop working.

cache: bundler

script:
- true