language: ruby

rvm: '2.1.5'

matrix:
  include:
    - sudo: false
      env:
        - ENV=docker
    - sudo: required
      dist: precise
      env:
        - ENV=precise-gce
    - sudo: required
      dist: trusty
      env:
        - ENV=trusty-gce

install:
  - true
script:
  - echo $PATH
